services:
    - type: web
      name: registration-backend
      env: python
      plan: free
      buildCommand: pip install -r app/requirements.txt
      startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
      envVars:
        - key: OPENAI_API_KEY
          sync: false
        - key: VALIDATION_ENGINE
          value: dspy
        - key: MLFLOW_ENABLED
          value: False
        - key: MLFLOW_EXPERIMENT_NAME
          value: DefaultExperiment
        - key: GRAPH_OUTPUT_DIR
          value: /app/LangGraph_Output
        - key: PYTHON_VERSION
          value: 3.10